site_description: "ILRuntime"
github: https://github.com/Ourpalm/ILRuntime
modify_github: https://github.com/Ourpalm/ILRuntime/tree/master/docs/sources/src/
copyright: © Copyright 2017 Ourpalm All Rights Reserved
copyright_desc: 掌趣科技2017